### ISSUE TITLE
upgrading from 2.0.1

### ISSUE THREAD

**Issue by lifun4kids** [chrislarrycarl/Helios-Calendar#14]
I upgraded to php 5.6 but when I try to upgrade to MySQL 5.5, my hosting company blocks the ability to choose "allow direct access." If I choose 5.0, I can choose "allow direct access," but the additional options show a Read-only option for the username.
Another issue is, I wanted to test the upgrade first, so I cloned the files and placed them in the same directory, but chose a different folder name than the one of my current calendar. (I customized some of the landing pages and didn't want to lose them. I have a backup too.) I made the necessary changes to the new config file so it connects to the current database that I'm using for my current calendar. I ran the setup for the test calendar, choosing the upgrade but it says the user probably doesn't have the proper privileges. How can that be if I'm using the same database that my old calendar is using? It corrupted my current calendar, so I restored the database and it's working fine. When I go to myPHPAdmin, I try to grant the privileges:  GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER ON username.* TO databaseName@host IDENTIFIED BY 'password'; but it says #1044 - Access denied for user. Any ideas what I'm doing wrong? Why would I have to give these privileges if I'm using a database that already should have the correct privileges set up, especially if it's a root user?

And if I get it to work, can I just rename my old calendar folder to something else, like OLD Calendar and then rename my test calendar folder to the name where my current calendar lives and then fixing my customized pages as needed? Thanks for your help.

**Comment by lifun4kids** [comment]
I was able to create the calendar in a test directory and created the admin username and password for a brand new database. I deleted the setup folder and when I tried to login, I keep getting 'Invalid Username or Password.' I also tried to retrieve the password by using the "lost your password," but don't even receive and email to reset it. Any help would be appreciated. Thank you.

**Comment by lifun4kids** [comment]
I also tried to create a new user through the database, but I still can't log in and no email is generated if I try the lost password option.

**Comment by lifun4kids** [comment]
I'm assuming this is my problem? How/where do I fix this?
https://github.com/chrislarrycarl/Helios-Calendar/wiki/Customize-Preferences#email

**Comment by ginarusso** [comment]
Do changes need to be made here to be able to receive the account creation email so I can log in? : inc/phpmailer/class.phpmailer.php. or inc/phpmailer/class.smtp.php. Any help would be greatly appreciated.

**Comment by lifun4kids** [comment]
okay, I believe it may be a hosting issue. I'll be in touch.
